### ISSUE TITLE
How to flash firmware to STM32F042F6

### ISSUE THREAD

**Issue by amxcs** [HardWrMan/PS1MemoryCard#2]
Hello,
I want to repeat the project, but I don't know how to flash the firmware on the chip.
I have several programmers, but it is not a problem to get another one if necessary.
I guess the code needs to be compiled, I also don't know how, but if I know what to do in a few steps I'll do it.
I will be grateful if you help me.
Thanks!

**Comment by HardWrMan** [comment]
Yes, you have to compile this project first before burn it into the MCU. I added the "Compiled" folder for precompiled firmwares you can use it. To burn it into the STM MCU you can use any SWD compatible programmers but I sugges to use ST-Link as it is the native one for this MCU. The legend of the SWD connector:
G - GND
D - SWDIO
C - SWCLK
R - RESET
P - 3.3v external power.
The original ST-Link does not provide power it use it for the level shifter so apply the 3.3v from the external power source or PS itself.

**Comment by amxcs** [comment]
Thank you so much!
